#!/usr/bin/env python3
"""gen_adder.py - generates a software ripple-carry full adder for Flux-1.

The FLUX-1 has no arithmetic instructions, only bits: SET/CLR a grid bit, and
GET/PUT/XOR (ACC op). A full adder is therefore built in *software*, bit by
bit, using branch trees instead of logic gates.

Per stage i the circuit implements:

    S_i    = A_i XOR B_i XOR C_in
    C_out  = majority(A_i, B_i, C_in)
           = (A_i AND B_i) OR (A_i AND C_in) OR (B_i AND C_in)

with majority computed by testing bits one at a time (a 1-bit comparator,
essentially the instruction set acting as the AND/OR gates).

GRID layout used by the generated program:
    0x00..0x03  operand A (4 bits, LSB first)
    0x04..0x07  operand B
    0x08        carry cell (C_in / C_out, reused each stage)
    0x09..0x0D  result S (5 bits: 4 sum bits + final carry)
    0x0F        permanent 1 cell (unused here, kept for convention)

Usage:  python tools/gen_adder.py <A> <B> [-o firmware/adder.asm]
        (defaults: A=5, B=3)

The generator prints the expected sum so you can verify with:
        flux firmware/adder.flux --grid-hex --steps 300
"""
import sys

PERM = 0x0F   # permanent 1 cell
CARRY = 0x08  # carry cell


def bits(v, n):
    return [(v >> i) & 1 for i in range(n)]


def emit_stage(f, i, a_addr, b_addr, s_addr):
    """Emit one full-adder stage. Labels are unique per stage."""
    p = lambda s: f.write(s + "\n")
    p("    ; ---- stage %d: S=%d=A%d XOR B%d XOR C, C_out=majority ----" % (i, s_addr, a_addr, b_addr))
    p("    ; S = A XOR B XOR C_in  (uses C_in before carry updates)")
    p("    GET  0x%02X" % a_addr)
    p("    XOR  0x%02X" % b_addr)
    p("    XOR  0x%02X" % CARRY)
    p("    PUT  0x%02X" % s_addr)
    p("    ; C_out = majority(A,B,C) by bit-testing:")
    p("    GET  0x%02X" % a_addr)
    p("    JZF  s%d_a0" % i)
    p("    ; A=1: C_out = B OR C")
    p("    GET  0x%02X" % b_addr)
    p("    JZF  s%d_a1b0" % i)
    p("    SET  0x%02X" % CARRY)     # A=1,B=1 -> 1
    p("    JMPF s%d_done" % i)
    p("s%d_a1b0:" % i)                # A=1,B=0 -> C_out = C_in (unchanged)
    p("    JMPF s%d_done" % i)
    p("s%d_a0:" % i)                  # A=0: C_out = B AND C
    p("    GET  0x%02X" % b_addr)
    p("    JZF  s%d_a0b0" % i)
    p("    ; A=0,B=1 -> C_out = C_in (unchanged)")
    p("    JMPF s%d_done" % i)
    p("s%d_a0b0:" % i)                # A=0,B=0 -> 0
    p("    CLR  0x%02X" % CARRY)
    p("s%d_done:" % i)
    p("")


def main():
    a = 5
    b = 3
    out = "firmware/adder.asm"
    args = [x for x in sys.argv[1:]]
    if args and args[0].lstrip('-').isdigit():
        a = int(args.pop(0))
    if args and args[0].lstrip('-').isdigit():
        b = int(args.pop(0))
    if args and args[0] == "-o" and len(args) > 1:
        out = args[1]

    n = 4
    ab = bits(a, n)
    bb = bits(b, n)

    with open(out, "w", encoding="utf-8") as f:
        p = lambda s: f.write(s + "\n")
        p("; adder.asm")
        p("; Software ripple-carry full adder (generated by tools/gen_adder.py).")
        p("; Adds two 4-bit operands stored in GRID bits, writes a 5-bit result")
        p("; back to GRID. No arithmetic hardware: the full adder is built from")
        p("; SET/CLR/GET/PUT/XOR and branch trees (the 1-bit CPU acting as gates).")
        p(";")
        p("; Operands: A = %d (0x%X), B = %d (0x%X)" % (a, a, b, b))
        p("; Expected: A + B = %d (0x%X)" % (a + b, a + b))
        p(";")
        p("; Layout: A=0x00..0x03  B=0x04..0x07  carry=0x08  S=0x09..0x0D")
        p("; Verify: flux firmware/adder.flux --grid-hex --steps 300")
        p("")
        p("START:")
        p("    ; ---- init: clear carry and result, set operands ----")
        p("    CLR  0x%02X" % CARRY)
        for i in range(5):
            p("    CLR  0x%02X" % (0x09 + i))
        for i in range(n):
            if ab[i]:
                p("    SET  0x%02X" % i)
            if bb[i]:
                p("    SET  0x%02X" % (0x04 + i))
        p("    ; ---- adder stages ----")
        p("")
        for i in range(n):
            emit_stage(f, i, i, 0x04 + i, 0x09 + i)
        p("    ; final carry out -> result bit 4")
        p("    GET  0x%02X" % CARRY)
        p("    PUT  0x0D")
        p("    ; ---- done: spin forever ----")
        p("DONE:")
        p("    JMPF DONE")
        p("")

    print("wrote %s  (A=%d + B=%d = %d)" % (out, a, b, a + b))


if __name__ == "__main__":
    main()