; adder.asm
; Software ripple-carry full adder (generated by tools/gen_adder.py).
; Adds two 4-bit operands stored in GRID bits, writes a 5-bit result
; back to GRID. No arithmetic hardware: the full adder is built from
; SET/CLR/GET/PUT/XOR and branch trees (the 1-bit CPU acting as gates).
;
; Operands: A = 5 (0x5), B = 3 (0x3)
; Expected: A + B = 8 (0x8)
;
; Layout: A=0x00..0x03  B=0x04..0x07  carry=0x08  S=0x09..0x0D
; Verify: flux firmware/adder.flux --grid-hex --steps 300

START:
    ; ---- init: clear carry and result, set operands ----
    CLR  0x08
    CLR  0x09
    CLR  0x0A
    CLR  0x0B
    CLR  0x0C
    CLR  0x0D
    SET  0x00
    SET  0x04
    SET  0x05
    SET  0x02
    ; ---- adder stages ----

    ; ---- stage 0: S=9=A0 XOR B4 XOR C, C_out=majority ----
    ; S = A XOR B XOR C_in  (uses C_in before carry updates)
    GET  0x00
    XOR  0x04
    XOR  0x08
    PUT  0x09
    ; C_out = majority(A,B,C) by bit-testing:
    GET  0x00
    JZF  s0_a0
    ; A=1: C_out = B OR C
    GET  0x04
    JZF  s0_a1b0
    SET  0x08
    JMPF s0_done
s0_a1b0:
    JMPF s0_done
s0_a0:
    GET  0x04
    JZF  s0_a0b0
    ; A=0,B=1 -> C_out = C_in (unchanged)
    JMPF s0_done
s0_a0b0:
    CLR  0x08
s0_done:

    ; ---- stage 1: S=10=A1 XOR B5 XOR C, C_out=majority ----
    ; S = A XOR B XOR C_in  (uses C_in before carry updates)
    GET  0x01
    XOR  0x05
    XOR  0x08
    PUT  0x0A
    ; C_out = majority(A,B,C) by bit-testing:
    GET  0x01
    JZF  s1_a0
    ; A=1: C_out = B OR C
    GET  0x05
    JZF  s1_a1b0
    SET  0x08
    JMPF s1_done
s1_a1b0:
    JMPF s1_done
s1_a0:
    GET  0x05
    JZF  s1_a0b0
    ; A=0,B=1 -> C_out = C_in (unchanged)
    JMPF s1_done
s1_a0b0:
    CLR  0x08
s1_done:

    ; ---- stage 2: S=11=A2 XOR B6 XOR C, C_out=majority ----
    ; S = A XOR B XOR C_in  (uses C_in before carry updates)
    GET  0x02
    XOR  0x06
    XOR  0x08
    PUT  0x0B
    ; C_out = majority(A,B,C) by bit-testing:
    GET  0x02
    JZF  s2_a0
    ; A=1: C_out = B OR C
    GET  0x06
    JZF  s2_a1b0
    SET  0x08
    JMPF s2_done
s2_a1b0:
    JMPF s2_done
s2_a0:
    GET  0x06
    JZF  s2_a0b0
    ; A=0,B=1 -> C_out = C_in (unchanged)
    JMPF s2_done
s2_a0b0:
    CLR  0x08
s2_done:

    ; ---- stage 3: S=12=A3 XOR B7 XOR C, C_out=majority ----
    ; S = A XOR B XOR C_in  (uses C_in before carry updates)
    GET  0x03
    XOR  0x07
    XOR  0x08
    PUT  0x0C
    ; C_out = majority(A,B,C) by bit-testing:
    GET  0x03
    JZF  s3_a0
    ; A=1: C_out = B OR C
    GET  0x07
    JZF  s3_a1b0
    SET  0x08
    JMPF s3_done
s3_a1b0:
    JMPF s3_done
s3_a0:
    GET  0x07
    JZF  s3_a0b0
    ; A=0,B=1 -> C_out = C_in (unchanged)
    JMPF s3_done
s3_a0b0:
    CLR  0x08
s3_done:

    ; final carry out -> result bit 4
    GET  0x08
    PUT  0x0D
    ; ---- done: spin forever ----
DONE:
    JMPF DONE

